import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface SakeSeed {
  name: string;
  slug: string;
  brewery: string;
  region: string;
  style: string;
  smv: number | null;
  acidity: number;
  price: number | null;
  flavors: string[];
  description: string;
}

const sakeData: SakeSeed[] = [
  {
    name: 'Koshi no Kanbai Sai Junmai Ginjo',
    slug: 'koshi-no-kanbai-sai',
    brewery: 'Asahi Shuzo (Niigata)',
    region: 'Niigata',
    style: 'junmai ginjo',
    smv: 5,
    acidity: 1.2,
    price: 20,
    flavors: ['light', 'crisp', 'dry'],
    description: 'Delicate and clean with refined rice sweetness and a crisp finish.',
  },
  {
    name: 'Tedorigawa Kinka Nama Daiginjo',
    slug: 'tedorigawa-kinka-nama-daiginjo',
    brewery: 'Yoshida Shuzo',
    region: 'Ishikawa',
    style: 'daiginjo',
    smv: 3,
    acidity: 1.3,
    price: 20,
    flavors: ['fruity', 'floral', 'light'],
    description: 'Fresh unpasteurized daiginjo with elegant aromatics and soft texture.',
  },
  {
    name: 'Heiwa Kid Junmai Daiginjo',
    slug: 'heiwa-kid-junmai-daiginjo',
    brewery: 'Heiwa Shuzo',
    region: 'Wakayama',
    style: 'junmai daiginjo',
    smv: 1,
    acidity: 1.4,
    price: 23,
    flavors: ['fruity', 'light', 'crisp'],
    description: 'Balanced and expressive with gentle fruit and smooth structure.',
  },
  {
    name: 'Tsuru-Ume Suppai',
    slug: 'tsuru-ume-suppai',
    brewery: 'Heiwa Shuzo',
    region: 'Wakayama',
    style: 'other',
    smv: -20,
    acidity: 1.8,
    price: 23,
    flavors: ['sweet', 'fruity', 'light'],
    description: 'Bright and tangy plum-based sake with refreshing acidity.',
  },
  {
    name: 'Dewazakura Green Ridge Junmai Ginjo',
    slug: 'dewazakura-green-ridge',
    brewery: 'Dewazakura Shuzo',
    region: 'Yamagata',
    style: 'junmai ginjo',
    smv: 5,
    acidity: 1.2,
    price: 22,
    flavors: ['floral', 'fruity', 'light'],
    description: 'Classic aromatic ginjo with soft floral notes and clean finish.',
  },
  {
    name: 'Dewazakura Sarasara Nigori',
    slug: 'dewazakura-sarasara-nigori',
    brewery: 'Dewazakura Shuzo',
    region: 'Yamagata',
    style: 'nigori',
    smv: -10,
    acidity: 1.5,
    price: 24,
    flavors: ['creamy', 'sweet', 'rice-forward'],
    description: 'Lightly cloudy and silky with gentle sweetness and smooth texture.',
  },
  {
    name: 'Kubota Junmai Daiginjo',
    slug: 'kubota-junmai-daiginjo',
    brewery: 'Asahi Shuzo (Niigata)',
    region: 'Niigata',
    style: 'junmai daiginjo',
    smv: 2,
    acidity: 1.2,
    price: 22,
    flavors: ['light', 'crisp', 'dry'],
    description: 'Clean and refined with subtle aromatics and a dry finish.',
  },
  {
    name: 'Kubota Senshin Junmai Daiginjo',
    slug: 'kubota-senshin',
    brewery: 'Asahi Shuzo (Niigata)',
    region: 'Niigata',
    style: 'junmai daiginjo',
    smv: 2,
    acidity: 1.1,
    price: 37,
    flavors: ['light', 'crisp', 'floral'],
    description: 'Ultra refined daiginjo with soft aroma and seamless texture.',
  },
  {
    name: 'Masumi Arabashiri Junmai Ginjo Nama',
    slug: 'masumi-arabashiri',
    brewery: 'Masumi (Miyasaka Brewing)',
    region: 'Nagano',
    style: 'junmai ginjo',
    smv: 3,
    acidity: 1.5,
    price: 28,
    flavors: ['fruity', 'crisp', 'light'],
    description: 'Lively and fresh with bright fruit and vibrant acidity.',
  },
  {
    name: 'Masumi Origarami Sparkling',
    slug: 'masumi-origarami-sparkling',
    brewery: 'Masumi (Miyasaka Brewing)',
    region: 'Nagano',
    style: 'sparkling',
    smv: -15,
    acidity: 1.6,
    price: 25,
    flavors: ['sweet', 'fruity', 'light'],
    description: 'Lightly sparkling with soft sweetness and creamy texture.',
  },
  {
    name: 'Akitabare Heaven of Tipsy Delight',
    slug: 'akitabare-tipsy-delight',
    brewery: 'Akitabare Shuzo',
    region: 'Akita',
    style: 'daiginjo',
    smv: 2,
    acidity: 1.3,
    price: 29,
    flavors: ['rich', 'umami', 'dry'],
    description: 'Rich and layered with depth and a smooth dry finish.',
  },
  {
    name: 'Akitabare Heaven of Joyous Delight',
    slug: 'akitabare-joyous-delight',
    brewery: 'Akitabare Shuzo',
    region: 'Akita',
    style: 'junmai daiginjo',
    smv: 3,
    acidity: 1.2,
    price: 55,
    flavors: ['rich', 'umami', 'light'],
    description: 'Elegant and structured with balanced umami and clean finish.',
  },
  {
    name: 'Dewazakura Yukimanman Snow Country',
    slug: 'dewazakura-yukimanman',
    brewery: 'Dewazakura Shuzo',
    region: 'Yamagata',
    style: 'daiginjo',
    smv: 4,
    acidity: 1.2,
    price: 57,
    flavors: ['floral', 'fruity', 'light'],
    description: 'Highly polished daiginjo with refined aroma and smooth finish.',
  },
  {
    name: 'Akabu Junmai Ginjo',
    slug: 'akabu-junmai-ginjo',
    brewery: 'Akabu Shuzo',
    region: 'Iwate',
    style: 'junmai ginjo',
    smv: 2,
    acidity: 1.4,
    price: 29,
    flavors: ['fruity', 'crisp', 'light'],
    description: 'Fresh and vibrant with clean fruit and a crisp finish.',
  },
  {
    name: 'GoSenHa Muni Peerless',
    slug: 'gosenha-muni-peerless',
    brewery: 'GoSenHa',
    region: 'Nagano',
    style: 'junmai daiginjo',
    smv: null,
    acidity: 1.3,
    price: 42,
    flavors: ['floral', 'fruity', 'light'],
    description: 'Refined and aromatic with elegant texture and balance.',
  },
  {
    name: 'GoSenHa Rain of 5000 Blades',
    slug: 'gosenha-rain-of-5000-blades',
    brewery: 'GoSenHa',
    region: 'Nagano',
    style: 'junmai daiginjo',
    smv: null,
    acidity: 1.4,
    price: 45,
    flavors: ['crisp', 'dry', 'light'],
    description: 'Focused and clean with precise structure and dry finish.',
  },
  {
    name: 'Kokuryu Cloudy Dragon Nigori',
    slug: 'kokuryu-cloudy-dragon',
    brewery: 'Kokuryu Shuzo',
    region: 'Fukui',
    style: 'nigori',
    smv: 1,
    acidity: 1.5,
    price: 24,
    flavors: ['creamy', 'rice-forward', 'light'],
    description: 'Soft and lightly cloudy with smooth texture and gentle sweetness.',
  },
  {
    name: 'Sohomare Tuxedo Kimoto Junmai Daiginjo',
    slug: 'sohomare-tuxedo',
    brewery: 'Sohomare Shuzo',
    region: 'Tochigi',
    style: 'junmai daiginjo',
    smv: 4,
    acidity: 1.6,
    price: 32,
    flavors: ['earthy', 'umami', 'rich'],
    description: 'Structured kimoto style with depth and savory complexity.',
  },
  {
    name: 'Sohomare Heart and Soul Junmai',
    slug: 'sohomare-heart-and-soul',
    brewery: 'Sohomare Shuzo',
    region: 'Tochigi',
    style: 'junmai',
    smv: 3,
    acidity: 1.7,
    price: 22,
    flavors: ['earthy', 'umami', 'rice-forward'],
    description: 'Classic kimoto junmai with depth and balanced acidity.',
  },
  {
    name: 'Tenko 40 Muroka Nama Genshu',
    slug: 'tenko-40',
    brewery: 'Kodama Jozo',
    region: 'Akita',
    style: 'genshu',
    smv: 5,
    acidity: 1.6,
    price: 197,
    flavors: ['rich', 'dry', 'umami'],
    description: 'Powerful unfiltered genshu with bold structure and depth.',
  },
  {
    name: 'Born Muroka Nama Genshu',
    slug: 'born-muroka-nama',
    brewery: 'Kato Kichibee Shoten',
    region: 'Fukui',
    style: 'genshu',
    smv: 2,
    acidity: 1.4,
    price: 143,
    flavors: ['rich', 'crisp', 'dry'],
    description: 'Full-bodied and clean with a polished dry finish.',
  },
  {
    name: 'Juyondai Gin-Sen Ginjo',
    slug: 'juyondai-gin-sen',
    brewery: 'Takagi Shuzo',
    region: 'Yamagata',
    style: 'ginjo',
    smv: 2,
    acidity: 1.2,
    price: 588,
    flavors: ['floral', 'fruity', 'light'],
    description: 'Highly aromatic and silky with refined balance.',
  },
  {
    name: 'Akitabare Winter Blossom',
    slug: 'akitabare-winter-blossom',
    brewery: 'Akitabare Shuzo',
    region: 'Akita',
    style: 'daiginjo',
    smv: 1,
    acidity: 1.3,
    price: 125,
    flavors: ['floral', 'light', 'crisp'],
    description: 'Delicate and floral with a clean and polished finish.',
  },
  {
    name: 'Hitakami Yasuke Clear Genshu',
    slug: 'hitakami-yasuke-clear',
    brewery: 'Hirako Shuzo',
    region: 'Miyagi',
    style: 'junmai daiginjo',
    smv: 5,
    acidity: 1.6,
    price: 295,
    flavors: ['dry', 'crisp', 'light'],
    description: 'Sharp and precise with a dry finish ideal for food pairing.',
  },
  {
    name: 'Iwa 5 Assemblage 3',
    slug: 'iwa-5-assemblage-3',
    brewery: 'IWA 5',
    region: 'Toyama',
    style: 'junmai daiginjo',
    smv: null,
    acidity: 1.4,
    price: 525,
    flavors: ['floral', 'fruity', 'rich'],
    description: 'Complex and layered with blended aromatic elegance.',
  },
  {
    name: 'Iwa 5 Assemblage 4',
    slug: 'iwa-5-assemblage-4',
    brewery: 'IWA 5',
    region: 'Toyama',
    style: 'junmai daiginjo',
    smv: null,
    acidity: 1.4,
    price: 485,
    flavors: ['floral', 'fruity', 'rich'],
    description: 'Refined blend with depth and balanced structure.',
  },
  {
    name: 'Iwa 5 Assemblage 5',
    slug: 'iwa-5-assemblage-5',
    brewery: 'IWA 5',
    region: 'Toyama',
    style: 'junmai daiginjo',
    smv: null,
    acidity: 1.4,
    price: 435,
    flavors: ['floral', 'fruity', 'rich'],
    description: 'Elegant assemblage with layered complexity and smooth finish.',
  },
  {
    name: 'Juyondai Hakuun Kyorai',
    slug: 'juyondai-hakuun-kyorai',
    brewery: 'Takagi Shuzo',
    region: 'Yamagata',
    style: 'junmai daiginjo',
    smv: null,
    acidity: 1.2,
    price: 2288,
    flavors: ['floral', 'fruity', 'rich'],
    description: 'Ultra premium sake with ethereal texture and complexity.',
  },
  {
    name: 'Juyondai Shichitare Nijukkan',
    slug: 'juyondai-shichitare-nijukkan',
    brewery: 'Takagi Shuzo',
    region: 'Yamagata',
    style: 'junmai daiginjo',
    smv: null,
    acidity: 1.2,
    price: 1750,
    flavors: ['rich', 'umami', 'complex'],
    description: 'Concentrated and luxurious with deep umami layers.',
  },
  {
    name: 'Juyondai Sakemirai Daigokujo',
    slug: 'juyondai-sakemirai',
    brewery: 'Takagi Shuzo',
    region: 'Yamagata',
    style: 'junmai daiginjo',
    smv: null,
    acidity: 1.2,
    price: 1688,
    flavors: ['floral', 'fruity', 'rich'],
    description: 'Opulent and expressive with rich texture and long finish.',
  },
  {
    name: 'Juyondai Ryuno Otoshigo Kamimorohaku',
    slug: 'juyondai-ryuno-otoshigo',
    brewery: 'Takagi Shuzo',
    region: 'Yamagata',
    style: 'junmai daiginjo',
    smv: null,
    acidity: 1.3,
    price: 1488,
    flavors: ['rich', 'umami', 'complex'],
    description: 'Deep and structured with layered umami and elegance.',
  },
  {
    name: 'Juyondai Banshu Aiyama Kamimorohaku',
    slug: 'juyondai-banshu-aiyama',
    brewery: 'Takagi Shuzo',
    region: 'Yamagata',
    style: 'junmai daiginjo',
    smv: null,
    acidity: 1.3,
    price: 1488,
    flavors: ['floral', 'fruity', 'rich'],
    description: 'Highly aromatic with rich fruit and refined texture.',
  },
  {
    name: 'Juyondai Honmaru Hiden Tamagaeshi',
    slug: 'juyondai-honmaru',
    brewery: 'Takagi Shuzo',
    region: 'Yamagata',
    style: 'honjozo',
    smv: 2,
    acidity: 1.2,
    price: 1088,
    flavors: ['light', 'dry', 'crisp'],
    description: 'Light and clean with subtle sweetness and smooth finish.',
  },
  {
    name: 'Katafune Lagoon Boat Koshu 2004',
    slug: 'katafune-lagoon-boat',
    brewery: 'Takeuchi Shuzo',
    region: 'Niigata',
    style: 'daiginjo',
    smv: null,
    acidity: 1.5,
    price: 990,
    flavors: ['rich', 'umami', 'earthy'],
    description: 'Aged koshu with developed depth and savory character.',
  },
  {
    name: 'Kokuryu Shizuku',
    slug: 'kokuryu-shizuku',
    brewery: 'Kokuryu Shuzo',
    region: 'Fukui',
    style: 'daiginjo',
    smv: 3,
    acidity: 1.2,
    price: 496,
    flavors: ['floral', 'fruity', 'light'],
    description: 'Exceptionally elegant with refined aroma and silky finish.',
  },
  {
    name: 'Kokuryu Hachijyuhachigo 88 Daiginjo',
    slug: 'kokuryu-88',
    brewery: 'Kokuryu Shuzo',
    region: 'Fukui',
    style: 'daiginjo',
    smv: 2,
    acidity: 1.2,
    price: 496,
    flavors: ['floral', 'light', 'crisp'],
    description: 'Highly polished with delicate aromatics and clean finish.',
  },
  {
    name: 'Koshi no Kanbai Kimiku',
    slug: 'koshi-no-kanbai-kimiku',
    brewery: 'Asahi Shuzo (Niigata)',
    region: 'Niigata',
    style: 'junmai daiginjo',
    smv: 2,
    acidity: 1.2,
    price: 280,
    flavors: ['light', 'crisp', 'floral'],
    description: 'Refined and balanced with subtle fruit and clean structure.',
  },
  {
    name: 'Kubota Tsugu',
    slug: 'kubota-tsugu',
    brewery: 'Asahi Shuzo (Niigata)',
    region: 'Niigata',
    style: 'junmai daiginjo',
    smv: 2,
    acidity: 1.1,
    price: 1125,
    flavors: ['floral', 'light', 'crisp'],
    description: 'Ultra premium with elegant aromatics and seamless texture.',
  },
  {
    name: 'Miyashita Divine Virtue Omachi',
    slug: 'miyashita-divine-virtue',
    brewery: 'Miyashita Shuzo',
    region: 'Okayama',
    style: 'junmai daiginjo',
    smv: null,
    acidity: 1.4,
    price: 902,
    flavors: ['rich', 'umami', 'fruity'],
    description: 'Full-bodied Omachi sake with rich texture and complexity.',
  },
  {
    name: 'Sohomare Ki-Itsu Kimoto 2017',
    slug: 'sohomare-ki-itsu',
    brewery: 'Sohomare Shuzo',
    region: 'Tochigi',
    style: 'junmai daiginjo',
    smv: 4,
    acidity: 1.6,
    price: 565,
    flavors: ['earthy', 'umami', 'rich'],
    description: 'Aged kimoto style with depth and savory richness.',
  },
  {
    name: 'Tatsuriki Nihon no Sakura Gold',
    slug: 'tatsuriki-sakura-gold',
    brewery: 'Tatsuriki Shuzo',
    region: 'Hyogo',
    style: 'junmai daiginjo',
    smv: 3,
    acidity: 1.3,
    price: 390,
    flavors: ['rich', 'umami', 'fruity'],
    description: 'Structured and powerful with refined fruit and depth.',
  },
  {
    name: 'Tedorigawa Chrysanthemum Meadow Yamahai Daiginjo',
    slug: 'tedorigawa-chrysanthemum-meadow',
    brewery: 'Yoshida Shuzo',
    region: 'Ishikawa',
    style: 'daiginjo',
    smv: 4,
    acidity: 1.6,
    price: 100,
    flavors: ['earthy', 'umami', 'rich'],
    description: 'Traditional yamahai style with depth and complexity.',
  },
  {
    name: 'Tedorigawa Mangekyo Daiginjo',
    slug: 'tedorigawa-mangekyo',
    brewery: 'Yoshida Shuzo',
    region: 'Ishikawa',
    style: 'daiginjo',
    smv: 3,
    acidity: 1.3,
    price: 736,
    flavors: ['floral', 'fruity', 'light'],
    description: 'Elegant daiginjo with aromatic lift and clean finish.',
  },
  {
    name: 'Tenko 20 Heavenly Grace',
    slug: 'tenko-20',
    brewery: 'Kodama Jozo',
    region: 'Akita',
    style: 'junmai daiginjo',
    smv: 5,
    acidity: 1.5,
    price: 491,
    flavors: ['rich', 'dry', 'umami'],
    description: 'Refined and powerful with layered depth and clean finish.',
  },
  {
    name: 'Akabu Cold Aged Junmai Daiginjo Yuinoka 35',
    slug: 'akabu-yuinoka-35',
    brewery: 'Akabu Shuzo',
    region: 'Iwate',
    style: 'junmai daiginjo',
    smv: null,
    acidity: 1.4,
    price: null,
    flavors: ['floral', 'fruity', 'light'],
    description: 'Cold-aged for precision with elegant aroma and smooth texture.',
  },
  {
    name: 'Tenko 35 Shizuku',
    slug: 'tenko-35',
    brewery: 'Kodama Jozo',
    region: 'Akita',
    style: 'daiginjo',
    smv: null,
    acidity: 1.4,
    price: null,
    flavors: ['floral', 'light', 'rich'],
    description: 'Drip-pressed daiginjo with refined aromatics and depth.',
  },
];

async function main() {
  console.log('Clearing existing data...');
  await prisma.sakeFlavorTag.deleteMany();
  await prisma.sake.deleteMany();
  await prisma.flavorTag.deleteMany();

  // Collect all unique flavor tags
  const allFlavors = new Set<string>();
  sakeData.forEach((s) => s.flavors.forEach((f) => allFlavors.add(f)));

  console.log(`Creating ${allFlavors.size} flavor tags...`);
  const flavorTagMap = new Map<string, string>();
  for (const flavor of Array.from(allFlavors)) {
    const tag = await prisma.flavorTag.create({
      data: { name: flavor },
    });
    flavorTagMap.set(flavor, tag.id);
  }

  // Create all sakes with their flavor tag associations
  console.log(`Seeding ${sakeData.length} sakes...`);
  for (const sake of sakeData) {
    await prisma.sake.create({
      data: {
        slug: sake.slug,
        name: sake.name,
        brewery: sake.brewery,
        region: sake.region,
        description: sake.description,
        smv: sake.smv,
        acidity: sake.acidity,
        price: sake.price,
        style: sake.style,
        flavorTags: {
          create: sake.flavors.map((f) => ({
            flavorTagId: flavorTagMap.get(f)!,
          })),
        },
      },
    });
  }

  console.log(`Seeded ${sakeData.length} sakes successfully!`);
}

main()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
