import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

interface SakeSeed {
  name: string;
  brewery: string;
  region: string;
  description: string;
  smv: number;
  acidity: number;
  price: number;
  riceType?: string;
  polishRatio?: number;
  style: string;
  abv?: number;
  flavors: string[];
}

const sakeData: SakeSeed[] = [
  {
    name: 'Dassai 23',
    brewery: 'Asahi Shuzo',
    region: 'Yamaguchi',
    description: 'Ultra-premium junmai daiginjo polished to an extraordinary 23%. Elegant and refined with delicate floral aromas and a silky, clean finish. One of Japan\'s most celebrated sakes.',
    smv: 4,
    acidity: 1.1,
    price: 45,
    riceType: 'Yamada Nishiki',
    polishRatio: 23,
    style: 'Junmai Daiginjo',
    abv: 16,
    flavors: ['floral', 'fruity', 'smooth'],
  },
  {
    name: 'Kubota Manju',
    brewery: 'Asahi Shuzo (Niigata)',
    region: 'Niigata',
    description: 'The pinnacle of Kubota\'s lineup. A beautifully balanced junmai daiginjo with subtle fruit notes, gentle sweetness, and an impossibly clean finish.',
    smv: 2,
    acidity: 1.2,
    price: 55,
    riceType: 'Gohyakumangoku',
    polishRatio: 33,
    style: 'Junmai Daiginjo',
    abv: 15.5,
    flavors: ['fruity', 'smooth', 'floral'],
  },
  {
    name: 'Hakkaisan Tokubetsu',
    brewery: 'Hakkaisan Brewery',
    region: 'Niigata',
    description: 'A refined honjozo from the snow country of Niigata. Clean, crisp, and easy to drink with gentle rice sweetness and a dry finish.',
    smv: 4,
    acidity: 1.0,
    price: 18,
    riceType: 'Gohyakumangoku',
    polishRatio: 55,
    style: 'Honjozo',
    abv: 15.5,
    flavors: ['crisp', 'dry', 'smooth'],
  },
  {
    name: 'Juyondai Honmaru',
    brewery: 'Takagi Shuzo',
    region: 'Yamagata',
    description: 'Highly sought-after sake with an exceptional balance of sweetness and umami. Tropical fruit aromas with a rich, layered palate.',
    smv: 2,
    acidity: 1.2,
    price: 65,
    riceType: 'Yamada Nishiki',
    polishRatio: 50,
    style: 'Junmai Ginjo',
    abv: 15,
    flavors: ['fruity', 'rich', 'umami'],
  },
  {
    name: 'Tedorigawa Yoshidagura',
    brewery: 'Yoshida Sake Brewery',
    region: 'Ishikawa',
    description: 'A traditional yamahai-style sake with deep umami character. Complex layers of earth, mushroom, and grain with a warming finish.',
    smv: 3,
    acidity: 1.8,
    price: 28,
    riceType: 'Yamada Nishiki',
    polishRatio: 40,
    style: 'Yamahai',
    abv: 16,
    flavors: ['earthy', 'umami', 'rich'],
  },
  {
    name: 'Born Gold',
    brewery: 'Katō Kichibee Shōten',
    region: 'Fukui',
    description: 'Aged junmai daiginjo with remarkable depth. Golden hue with notes of honey, dried fruit, and toasted nuts. Rich yet elegant.',
    smv: -2,
    acidity: 1.3,
    price: 42,
    riceType: 'Yamada Nishiki',
    polishRatio: 35,
    style: 'Junmai Daiginjo',
    abv: 15,
    flavors: ['rich', 'sweet', 'fruity'],
  },
  {
    name: 'Masumi Okuden Kantsukuri',
    brewery: 'Miyasaka Brewing',
    region: 'Nagano',
    description: 'Classic Nagano junmai made during the coldest months. Round and full-bodied with apple and melon notes. Perfect warm or chilled.',
    smv: -1,
    acidity: 1.5,
    price: 22,
    riceType: 'Miyama Nishiki',
    polishRatio: 70,
    style: 'Junmai',
    abv: 15,
    flavors: ['fruity', 'smooth', 'umami'],
  },
  {
    name: 'Suigei Tokubetsu Junmai',
    brewery: 'Suigei Brewing',
    region: 'Kochi',
    description: 'Bone-dry sake from Kochi, famous for its drinking culture. Crisp and refreshing with a sharp, clean finish that pairs wonderfully with seafood.',
    smv: 7,
    acidity: 1.5,
    price: 20,
    riceType: 'Matsuyama Mitsui',
    polishRatio: 55,
    style: 'Junmai',
    abv: 15.5,
    flavors: ['crisp', 'dry'],
  },
  {
    name: 'Dewazakura Oka',
    brewery: 'Dewazakura Sake Brewery',
    region: 'Yamagata',
    description: 'Cherry bouquet ginjo that helped popularize the ginjo style. Fragrant cherry blossom and green apple aromas with a light, fresh palate.',
    smv: 5,
    acidity: 1.2,
    price: 24,
    riceType: 'Dewasansan',
    polishRatio: 50,
    style: 'Ginjo',
    abv: 15.5,
    flavors: ['floral', 'fruity', 'crisp'],
  },
  {
    name: 'Nanbu Bijin Tokubetsu Junmai',
    brewery: 'Nanbu Bijin',
    region: 'Iwate',
    description: 'Graceful sake from the Northern Tohoku region. Clean mineral notes with gentle rice sweetness and a touch of citrus on the finish.',
    smv: 4,
    acidity: 1.5,
    price: 26,
    riceType: 'Gin Otome',
    polishRatio: 55,
    style: 'Junmai',
    abv: 15.5,
    flavors: ['crisp', 'smooth'],
  },
  {
    name: 'Tengumai Yamahai Junmai',
    brewery: 'Shata Shuzo',
    region: 'Ishikawa',
    description: 'Bold yamahai junmai with robust character. Deep flavors of toasted grain, soy, and nuts with a satisfying umami backbone. Excellent warm.',
    smv: 3,
    acidity: 1.9,
    price: 19,
    riceType: 'Gohyakumangoku',
    polishRatio: 60,
    style: 'Yamahai',
    abv: 15.5,
    flavors: ['earthy', 'umami', 'spicy'],
  },
  {
    name: 'Kokuryu Junmai Ginjo',
    brewery: 'Kokuryu Sake Brewing',
    region: 'Fukui',
    description: 'Elegant and well-structured ginjo from Fukui\'s famous Kokuryu. Pear and white peach aromas with a balanced, medium-bodied palate.',
    smv: 3,
    acidity: 1.2,
    price: 32,
    riceType: 'Gohyakumangoku',
    polishRatio: 55,
    style: 'Junmai Ginjo',
    abv: 15.5,
    flavors: ['fruity', 'floral', 'smooth'],
  },
  {
    name: 'Ozeki Nigori',
    brewery: 'Ozeki Corporation',
    region: 'Hyogo',
    description: 'Creamy unfiltered sake with a cloudy white appearance. Sweet and rich with tropical fruit and coconut notes. A dessert-like indulgence.',
    smv: -12,
    acidity: 1.0,
    price: 14,
    polishRatio: 70,
    style: 'Nigori',
    abv: 14.5,
    flavors: ['sweet', 'rich', 'fruity'],
  },
  {
    name: 'Mio Sparkling',
    brewery: 'Takara Shuzo',
    region: 'Kyoto',
    description: 'Light and bubbly sparkling sake with low alcohol. Refreshing sweetness with hints of peach and muscat grape. Perfect aperitif.',
    smv: -70,
    acidity: 1.0,
    price: 12,
    style: 'Sparkling',
    abv: 5,
    flavors: ['sweet', 'fruity', 'floral'],
  },
  {
    name: 'Koshi no Kanbai Sai',
    brewery: 'Ishimoto Sake Brewing',
    region: 'Niigata',
    description: 'Legendary Niigata sake with impeccable purity. Ultra-clean and refreshing with mineral undertones and a lingering, dry finish.',
    smv: 8,
    acidity: 1.3,
    price: 48,
    riceType: 'Gohyakumangoku',
    polishRatio: 40,
    style: 'Junmai Daiginjo',
    abv: 15,
    flavors: ['crisp', 'dry', 'smooth'],
  },
  {
    name: 'Tamanohikari Junmai Ginjo',
    brewery: 'Tamanohikari Sake Brewing',
    region: 'Kyoto',
    description: 'Pioneer of the junmai ginjo style. Lively and aromatic with citrus and herb notes. A benchmark for Kyoto craft sake.',
    smv: 3,
    acidity: 1.4,
    price: 30,
    riceType: 'Bizen Omachi',
    polishRatio: 50,
    style: 'Junmai Ginjo',
    abv: 16,
    flavors: ['floral', 'crisp', 'spicy'],
  },
  {
    name: 'Rihaku Dreamy Clouds',
    brewery: 'Rihaku Sake Brewery',
    region: 'Shimane',
    description: 'Lightly cloudy tokubetsu junmai with a dreamy, soft texture. Sweet rice pudding notes balanced by bright acidity and a gentle finish.',
    smv: -3,
    acidity: 1.5,
    price: 20,
    riceType: 'Sakanishiki',
    polishRatio: 59,
    style: 'Nigori',
    abv: 15.5,
    flavors: ['sweet', 'smooth', 'fruity'],
  },
  {
    name: 'Akashi-Tai Honjozo',
    brewery: 'Akashi Tai Brewery',
    region: 'Hyogo',
    description: 'Easy-drinking honjozo from the Akashi coast. Light and crisp with a touch of salinity. An ideal everyday sake that pairs with everything.',
    smv: 1,
    acidity: 1.3,
    price: 16,
    riceType: 'Hyogo Yume Nishiki',
    polishRatio: 65,
    style: 'Honjozo',
    abv: 14.5,
    flavors: ['crisp', 'smooth'],
  },
  {
    name: 'Wakatake Onikoroshi',
    brewery: 'Omuraya Brewing',
    region: 'Shizuoka',
    description: 'Demon Slayer junmai daiginjo — assertive and bold with a bone-dry profile. Herbal and peppery notes with a clean, sharp finish.',
    smv: 10,
    acidity: 1.6,
    price: 35,
    riceType: 'Yamada Nishiki',
    polishRatio: 45,
    style: 'Junmai Daiginjo',
    abv: 16.5,
    flavors: ['dry', 'spicy', 'crisp'],
  },
  {
    name: 'Fukucho Seaside Junmai',
    brewery: 'Imada Sake Brewing',
    region: 'Hiroshima',
    description: 'Brewed with lemon-infused water and a female toji. Bright, minerally, and refreshing with citrus zest and ocean breeze character.',
    smv: 2,
    acidity: 1.7,
    price: 25,
    riceType: 'Hattan Nishiki',
    polishRatio: 60,
    style: 'Junmai',
    abv: 15,
    flavors: ['crisp', 'fruity'],
  },
  {
    name: 'Senkin Modern',
    brewery: 'Senkin Brewery',
    region: 'Tochigi',
    description: 'New-wave sake with a wine-like acidity and tropical fruit complexity. Pineapple, lychee, and citrus notes with a juicy, off-dry finish.',
    smv: -3,
    acidity: 1.8,
    price: 34,
    riceType: 'Yamada Nishiki',
    polishRatio: 50,
    style: 'Junmai Ginjo',
    abv: 15,
    flavors: ['fruity', 'floral', 'sweet'],
  },
  {
    name: 'Daishichi Kimoto',
    brewery: 'Daishichi Sake Brewery',
    region: 'Fukushima',
    description: 'Classic kimoto-style sake with centuries of tradition. Deep, complex umami with roasted chestnut and caramel notes. Supreme warm.',
    smv: 2,
    acidity: 1.6,
    price: 27,
    riceType: 'Gohyakumangoku',
    polishRatio: 69,
    style: 'Kimoto',
    abv: 15,
    flavors: ['umami', 'earthy', 'rich'],
  },
  {
    name: 'Harushika Junmai',
    brewery: 'Imanishi Seibei Shoten',
    region: 'Nara',
    description: 'Spring deer junmai from Japan\'s oldest sake-brewing region. Gentle and balanced with white flower aromas and a soft, rounded palate.',
    smv: 1,
    acidity: 1.3,
    price: 19,
    riceType: 'Hinohikari',
    polishRatio: 65,
    style: 'Junmai',
    abv: 15,
    flavors: ['floral', 'smooth'],
  },
  {
    name: 'Otokoyama Tokubetsu Junmai',
    brewery: 'Otokoyama Sake Brewery',
    region: 'Hokkaido',
    description: 'Brewed with pristine Hokkaido mountain water. Ultra-dry with a sharp, clean character. Crisp minerality and a bone-dry finish.',
    smv: 10,
    acidity: 1.4,
    price: 23,
    riceType: 'Suisei',
    polishRatio: 55,
    style: 'Junmai',
    abv: 16,
    flavors: ['dry', 'crisp'],
  },
  {
    name: 'Kanbara Bride of the Fox',
    brewery: 'Kaetsu Brewing',
    region: 'Niigata',
    description: 'Junmai ginjo with a poetic name and elegant character. Notes of ripe pear and jasmine with a silky mouthfeel and a dry, polished finish.',
    smv: 2,
    acidity: 1.4,
    price: 29,
    riceType: 'Takane Nishiki',
    polishRatio: 55,
    style: 'Junmai Ginjo',
    abv: 15.5,
    flavors: ['floral', 'fruity', 'smooth'],
  },
  {
    name: 'Sho Chiku Bai Nama',
    brewery: 'Takara Sake USA',
    region: 'California',
    description: 'Fresh unpasteurized nama sake brewed in Berkeley. Lively and bright with green apple and melon flavors. Must be kept chilled.',
    smv: 0,
    acidity: 1.3,
    price: 15,
    polishRatio: 60,
    style: 'Nama',
    abv: 14.5,
    flavors: ['fruity', 'crisp', 'sweet'],
  },
  {
    name: 'Hourai Hida no Homare',
    brewery: 'Watanabe Sake Brewing',
    region: 'Gifu',
    description: 'Mountain-brewed ginjo from the Hida highlands. Clean and precise with alpine flower notes and a refreshing, mineral finish.',
    smv: 5,
    acidity: 1.1,
    price: 26,
    riceType: 'Hida Homare',
    polishRatio: 55,
    style: 'Ginjo',
    abv: 15,
    flavors: ['floral', 'crisp', 'smooth'],
  },
  {
    name: 'Shichida Junmai',
    brewery: 'Tenzan Sake Brewery',
    region: 'Saga',
    description: 'Kyushu-style junmai with rich umami depth. Full-bodied with earthy mushroom and toasted rice notes. Pairs brilliantly with grilled meats.',
    smv: -1,
    acidity: 1.7,
    price: 24,
    riceType: 'Yamada Nishiki',
    polishRatio: 65,
    style: 'Junmai',
    abv: 16,
    flavors: ['umami', 'earthy', 'rich'],
  },
  {
    name: 'Yuki no Bosha',
    brewery: 'Saiya Sake Brewery',
    region: 'Akita',
    description: 'Cabin in the Snow — a beautifully named junmai ginjo. Delicate and well-balanced with pear and green tea notes and a clean finish.',
    smv: 1,
    acidity: 1.5,
    price: 32,
    riceType: 'Akita Sake Komachi',
    polishRatio: 55,
    style: 'Junmai Ginjo',
    abv: 15.5,
    flavors: ['smooth', 'floral', 'crisp'],
  },
  {
    name: 'Kamoizumi Shusen',
    brewery: 'Kamoizumi Sake Brewing',
    region: 'Hiroshima',
    description: 'Rich and complex aged junmai with an amber hue. Sherry-like oxidative notes with dried fruit, caramel, and savory umami layers.',
    smv: -5,
    acidity: 2.0,
    price: 30,
    riceType: 'Shinsenbon',
    polishRatio: 60,
    style: 'Junmai',
    abv: 16.5,
    flavors: ['rich', 'umami', 'earthy', 'sweet'],
  },
  {
    name: 'Isojiman Junmai Ginjo',
    brewery: 'Isojiman Sake Brewing',
    region: 'Shizuoka',
    description: 'Pristine Shizuoka ginjo with Mt. Fuji spring water. Crystal clear with melon and white grape aromas and a silky, precise finish.',
    smv: 5,
    acidity: 1.2,
    price: 38,
    riceType: 'Yamada Nishiki',
    polishRatio: 50,
    style: 'Junmai Ginjo',
    abv: 16,
    flavors: ['fruity', 'smooth', 'crisp'],
  },
  {
    name: 'Kirinzan Junmai',
    brewery: 'Kirinzan Sake Brewery',
    region: 'Niigata',
    description: 'Classic dry Niigata junmai with a straightforward elegance. Clean rice flavor with mild citrus notes and a smooth, easy-drinking finish.',
    smv: 6,
    acidity: 1.3,
    price: 17,
    riceType: 'Gohyakumangoku',
    polishRatio: 60,
    style: 'Junmai',
    abv: 15.5,
    flavors: ['dry', 'crisp', 'smooth'],
  },
  {
    name: 'Hakutsuru Sayuri',
    brewery: 'Hakutsuru Sake Brewing',
    region: 'Hyogo',
    description: 'Little Lilly nigori with a sweet, creamy character. Lush and fruity with strawberry yogurt notes. A crowd-pleasing introduction to sake.',
    smv: -8,
    acidity: 1.0,
    price: 13,
    polishRatio: 70,
    style: 'Nigori',
    abv: 12.5,
    flavors: ['sweet', 'fruity', 'smooth'],
  },
  {
    name: 'Amabuki Strawberry Ginjo',
    brewery: 'Amabuki Sake Brewery',
    region: 'Saga',
    description: 'Brewed with strawberry flower yeast for a unique aromatic profile. Delicate berry and rose petal aromas with a soft, floral palate.',
    smv: -5,
    acidity: 1.4,
    price: 28,
    riceType: 'Saga no Hana',
    polishRatio: 55,
    style: 'Ginjo',
    abv: 15,
    flavors: ['floral', 'fruity', 'sweet'],
  },
  {
    name: 'Tengu Sake Junmai',
    brewery: 'Kizakura Brewery',
    region: 'Kyoto',
    description: 'Hearty Fushimi junmai with the soft water character of Kyoto. Rounded and mellow with steamed rice and chestnut notes.',
    smv: 1,
    acidity: 1.4,
    price: 16,
    polishRatio: 65,
    style: 'Junmai',
    abv: 15,
    flavors: ['smooth', 'umami'],
  },
  {
    name: 'Tatenokawa Phoenix',
    brewery: 'Tatenokawa Sake Brewery',
    region: 'Yamagata',
    description: 'Ambitious daiginjo polished to 18%. Extraordinarily refined with delicate banana and vanilla notes. A showcase of polishing mastery.',
    smv: -1,
    acidity: 1.1,
    price: 58,
    riceType: 'Dewasansan',
    polishRatio: 18,
    style: 'Daiginjo',
    abv: 15.5,
    flavors: ['floral', 'fruity', 'smooth'],
  },
  {
    name: 'Kurosawa Junmai Kimoto',
    brewery: 'Kurosawa Sake Brewing',
    region: 'Nagano',
    description: 'Rustic kimoto with deep, earthy complexity. Hints of dark chocolate, dried mushroom, and toasted grain. Outstanding with stews and braises.',
    smv: 5,
    acidity: 1.8,
    price: 21,
    riceType: 'Miyama Nishiki',
    polishRatio: 65,
    style: 'Kimoto',
    abv: 15,
    flavors: ['earthy', 'umami', 'spicy'],
  },
  {
    name: 'Manotsuru Bulzai',
    brewery: 'Obata Sake Brewery',
    region: 'Niigata',
    description: 'From Sado Island off Niigata coast. Dry and crisp with ocean mineral notes. Made sustainably to protect the endangered crested ibis.',
    smv: 7,
    acidity: 1.3,
    price: 25,
    riceType: 'Gohyakumangoku',
    polishRatio: 58,
    style: 'Junmai',
    abv: 15.5,
    flavors: ['dry', 'crisp'],
  },
  {
    name: 'Kozaemon Junmai',
    brewery: 'Nakashima Brewing',
    region: 'Gifu',
    description: 'Mountain-brewed organic junmai with a natural, minimalist approach. Rice-forward with gentle sweetness and a clean, earthy finish.',
    smv: 0,
    acidity: 1.5,
    price: 23,
    riceType: 'Akebono',
    polishRatio: 60,
    style: 'Junmai',
    abv: 15,
    flavors: ['earthy', 'smooth', 'umami'],
  },
  {
    name: 'Kikusui Funaguchi',
    brewery: 'Kikusui Sake',
    region: 'Niigata',
    description: 'Bold, undiluted nama-chozo with a punch. Golden color with rich honey, caramel, and tropical fruit notes. High ABV and intense flavor.',
    smv: -3,
    acidity: 1.8,
    price: 14,
    polishRatio: 70,
    style: 'Nama',
    abv: 19,
    flavors: ['rich', 'sweet', 'fruity'],
  },
  {
    name: 'Gasanryu Gokugetsu',
    brewery: 'Gasanryu Sake Brewery',
    region: 'Yamagata',
    description: 'Moon on the summit — a poetic daiginjo with ethereal beauty. Whisper-light with jasmine and honeydew notes and a vanishing finish.',
    smv: 3,
    acidity: 1.1,
    price: 50,
    riceType: 'Dewasansan',
    polishRatio: 40,
    style: 'Daiginjo',
    abv: 16,
    flavors: ['floral', 'smooth', 'fruity'],
  },
  {
    name: 'Konteki Pearls of Simplicity',
    brewery: 'Tsukinokatsura',
    region: 'Kyoto',
    description: 'Sparkling junmai daiginjo with fine, persistent bubbles. Bright citrus and green apple with a clean, effervescent finish.',
    smv: -8,
    acidity: 1.3,
    price: 35,
    riceType: 'Iwai',
    polishRatio: 50,
    style: 'Sparkling',
    abv: 12,
    flavors: ['fruity', 'crisp', 'sweet'],
  },
  {
    name: 'Taiheizan Kimoto',
    brewery: 'Kodama Brewing',
    region: 'Akita',
    description: 'Robust kimoto from snowy Akita. Deep savory character with notes of soy, walnut, and dried seaweed. A sake sommelier favorite.',
    smv: 4,
    acidity: 1.9,
    price: 26,
    riceType: 'Akita Sake Komachi',
    polishRatio: 60,
    style: 'Kimoto',
    abv: 15.5,
    flavors: ['umami', 'earthy', 'spicy'],
  },
  {
    name: 'Hyakujuro Junmai Ginjo',
    brewery: 'Hayashi Honten',
    region: 'Gifu',
    description: 'Underrated gem from Gifu with impeccable balance. Fresh green herb and melon notes with a medium body and lingering finish.',
    smv: 2,
    acidity: 1.3,
    price: 29,
    riceType: 'Hida Homare',
    polishRatio: 55,
    style: 'Junmai Ginjo',
    abv: 15.5,
    flavors: ['fruity', 'crisp', 'floral'],
  },
  {
    name: 'Watari Bune Junmai Ginjo',
    brewery: 'Huchu Homare Brewery',
    region: 'Ibaraki',
    description: 'Made from a revived heritage rice variety. Rich and structured with ripe peach and honeyed grain notes. A tribute to sake history.',
    smv: 0,
    acidity: 1.6,
    price: 33,
    riceType: 'Watari Bune',
    polishRatio: 55,
    style: 'Junmai Ginjo',
    abv: 16,
    flavors: ['rich', 'fruity', 'umami'],
  },
  {
    name: 'Niwa no Uguisu 50',
    brewery: 'Yamaguchi Sake Brewing',
    region: 'Fukuoka',
    description: 'Nightingale of the garden — a bright and cheerful junmai ginjo. Tropical mango and passionfruit aromas with a juicy, modern profile.',
    smv: -2,
    acidity: 1.5,
    price: 28,
    riceType: 'Yamada Nishiki',
    polishRatio: 50,
    style: 'Junmai Ginjo',
    abv: 15,
    flavors: ['fruity', 'sweet', 'floral'],
  },
  {
    name: 'Taka Junmai',
    brewery: 'Nagayama Honke Brewing',
    region: 'Yamaguchi',
    description: 'Modern-style junmai with bright acidity and clean fruit. Grapefruit and lemon zest notes with a snappy, food-friendly finish.',
    smv: 4,
    acidity: 1.8,
    price: 22,
    riceType: 'Yamada Nishiki',
    polishRatio: 60,
    style: 'Junmai',
    abv: 15,
    flavors: ['crisp', 'fruity', 'dry'],
  },
  {
    name: 'Jozen Mizuno Gotoshi',
    brewery: 'Shirataki Sake Brewery',
    region: 'Niigata',
    description: 'Pure as driven snow — a crystal clear junmai ginjo. Incredibly clean with soft pear notes and a whisper of sweetness on the finish.',
    smv: 3,
    acidity: 1.0,
    price: 21,
    riceType: 'Gohyakumangoku',
    polishRatio: 55,
    style: 'Junmai Ginjo',
    abv: 14.5,
    flavors: ['smooth', 'crisp', 'floral'],
  },
  {
    name: 'Ichinokura Himezen',
    brewery: 'Ichinokura Sake Brewery',
    region: 'Miyagi',
    description: 'Specifically designed for warm serving. Gentle and comforting with toasted grain and brown sugar notes that bloom when heated.',
    smv: 1,
    acidity: 1.3,
    price: 17,
    polishRatio: 65,
    style: 'Junmai',
    abv: 15,
    flavors: ['sweet', 'smooth', 'umami'],
  },
  {
    name: 'Tsuki no Katsura Yanagi',
    brewery: 'Masuda Tokubee Shoten',
    region: 'Kyoto',
    description: 'Traditional Fushimi-style junmai with silky Kyoto water. Graceful and understated with white rice and subtle floral nuances.',
    smv: 1,
    acidity: 1.2,
    price: 24,
    riceType: 'Iwai',
    polishRatio: 60,
    style: 'Junmai',
    abv: 15.5,
    flavors: ['floral', 'smooth'],
  },
];

async function main() {
  console.log('🍶 Starting sake menu seed...');
  console.log(`   Seeding ${sakeData.length} sakes...`);

  // Clear existing data
  await prisma.sakeFlavorTag.deleteMany();
  await prisma.sake.deleteMany();
  await prisma.flavorTag.deleteMany();

  // Create all unique flavor tags
  const allFlavors = new Set<string>();
  sakeData.forEach((s) => s.flavors.forEach((f) => allFlavors.add(f)));

  const flavorTagMap = new Map<string, string>();
  for (const flavor of Array.from(allFlavors)) {
    const tag = await prisma.flavorTag.create({
      data: { name: flavor },
    });
    flavorTagMap.set(flavor, tag.id);
  }
  console.log(`   Created ${allFlavors.size} flavor tags`);

  // Create all sakes with their flavor tag associations
  for (const sake of sakeData) {
    const slug = slugify(`${sake.name}-${sake.brewery}`);
    await prisma.sake.create({
      data: {
        slug,
        name: sake.name,
        brewery: sake.brewery,
        region: sake.region,
        description: sake.description,
        smv: sake.smv,
        acidity: sake.acidity,
        price: sake.price,
        riceType: sake.riceType || null,
        polishRatio: sake.polishRatio || null,
        style: sake.style,
        abv: sake.abv || null,
        flavorTags: {
          create: sake.flavors.map((f) => ({
            flavorTagId: flavorTagMap.get(f)!,
          })),
        },
      },
    });
  }

  console.log(`   Seeded ${sakeData.length} sakes successfully!`);
  console.log('🎉 Seed complete!');
}

main()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
